server:
  port: 8181

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html




logging:
  level:
    root: info
    cn.jiayeli.dataLeaf.dao: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
